### ISSUE TITLE
channels

### ISSUE THREAD

**Issue by 77loggedaloha** [EdgarLefevre/CycleGAN#1]
RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[1, 1, 256, 256] to have 3 channels, but got 1 channels instead.
How can I modify the code?

**Comment by EdgarLefevre** [comment]
Hello, 

In `src/models/gan.py`, you have the model definition, by modifying the number of channels in the first and last layer of the generator and the first layer of the discriminator (from 1 to 3).

For example : 
From:
```python
self.down_path = nn.Sequential(
            nn.Conv2d(1, 64, kernel_size=7, stride=1, padding=3),
            nn.Conv2d(64, 128, kernel_size=3, stride=2, padding=1),
            nn.Conv2d(128, 256, kernel_size=3, stride=2, padding=1),
        )
```

To: 

```python
self.down_path = nn.Sequential(
            nn.Conv2d(3, 64, kernel_size=7, stride=1, padding=3),
            nn.Conv2d(64, 128, kernel_size=3, stride=2, padding=1),
            nn.Conv2d(128, 256, kernel_size=3, stride=2, padding=1),
        )
```
